export const SOMETHING_REQUEST = 'SOMETHING_REQUEST';
export const SOMETHING_FAILURE = 'SOMETHING_FAILURE';
export const RESET_INDEX = 'RESET_INDEX';
export const CHANGE_LOCALE = 'CHANGE_LOCALE';
export const FETCH_BUILDING_SUCCESS = 'FETCH_BUILDING_SUCCESS';
export const ETA_TRANSPORTS_SUCCESS = 'ETA_TRANSPORTS_SUCCESS';
export const NOTIFICATION_STATUS = 'NOTIFICATION_STATUS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REPORTING_SUCCESS = 'REPORTING_SUCCESS';
export const REPORTING_FAILURE = 'REPORTING_FAILURE';
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS';
export const SEARCH_BUILDING_SUCCESS = 'SEARCH_BUILDING_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const RETRIEVE_PASSWORD_SUCCESS = 'RETRIEVE_PASSWORD_SUCCESS';
export const GET_ALL_BUILDING_SUCCESS = 'GET_ALL_BUILDING_SUCCESS';
export const SELECT_BUILDING = 'SELECT_BUILDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
//callback
export const CONFIRM_CALLBACK_REQUEST = 'CONFIRM_CALLBACK_REQUEST';
export const CONFIRM_CALLBACK_SUCCESS = 'CONFIRM_CALLBACK_SUCCESS';
export const CONFIRM_CALLBACK_FAILURE = 'CONFIRM_CALLBACK_FAILURE';
//request
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const FETCH_BUILDING_REQUEST = 'FETCH_BUILDING_REQUEST';
export const ETA_TRANSPORTS_REQUEST = 'ETA_TRANSPORTS_REQUEST';
export const GET_ALL_BUILDING_REQUEST = 'GET_ALL_BUILDING_REQUEST';
export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST';
export const LINKEDIN_LOGIN_REQUEST = 'LINKEDIN_LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
//verify
export const VERIFY_USER_REQUEST = 'VERIFY_USER_REQUEST';
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const VERIFY_USER_FAILURE = 'VERIFY_USER_FAILURE';
//verify phone number
export const VERIFY_PHONE_NUMBER_REQUEST = 'VERIFY_PHONE_NUMBER_REQUEST';
export const VERIFY_PHONE_NUMBER_SUCCESS = 'VERIFY_PHONE_NUMBER_SUCCESS';
export const VERIFY_PHONE_NUMBER_FAILURE = 'VERIFY_PHONE_NUMBER_FAILURE';
//check code verify number
export const CHECK_VERIFY_NUMBER_REQUEST = 'CHECK_VERIFY_NUMBER_REQUEST';
export const CHECK_VERIFY_NUMBER_SUCCESS = 'CHECK_VERIFY_NUMBER_SUCCESS';
export const CHECK_VERIFY_NUMBER_FAILURE = 'CHECK_VERIFY_NUMBER_FAILURE';
